version: '3.8'

services:
  familytodo:
    build: .
    container_name: familytodo
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_PATH=/app/data/familytodo.db
      - UPLOAD_DIR=/app/uploads
      - CORS_ORIGIN=http://localhost:4000
      - SOCKET_CORS_ORIGIN=http://localhost:4000
    networks:
      - familytodo-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Optional: Caddy for HTTPS (uncomment if needed)
  # caddy:
  #   image: caddy:2-alpine
  #   container_name: familytodo-caddy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   networks:
  #     - familytodo-network

networks:
  familytodo-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: