name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  DOCKER_BUILDKIT: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Run backend tests
        working-directory: ./backend
        run: npm test --if-present
      
      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test --if-present
      
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.VPS_HOST }}" ]; then
            echo "::error::VPS_HOST secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VPS_USER }}" ]; then
            echo "::error::VPS_USER secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VPS_SSH_KEY }}" ]; then
            echo "::error::VPS_SSH_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.TAILSCALE_AUTH_KEY }}" ]; then
            echo "::warning::TAILSCALE_AUTH_KEY not set - will try direct connection"
            echo "HAS_TAILSCALE=false" >> $GITHUB_ENV
          else
            echo "✅ Tailscale auth key configured"
            echo "HAS_TAILSCALE=true" >> $GITHUB_ENV
          fi
          echo "✅ All required secrets are configured"
      
      # Option 1: Connect via Tailscale (if auth key provided)
      - name: Connect to Tailscale
        if: ${{ env.HAS_TAILSCALE == 'true' }}
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          tags: tag:ci
      
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          
          # Write SSH key with proper format
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Check key format and convert if needed
          if ! ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>&1; then
            echo "::warning::SSH key format issue detected, trying to fix..."
            # Try to fix key format (ensure proper line endings)
            sed -i 's/\r$//' ~/.ssh/id_rsa
            
            # Check again
            if ! ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>&1; then
              echo "::error::Invalid SSH private key format. Please check the VPS_SSH_KEY secret."
              echo "::error::Ensure the key includes '-----BEGIN' and '-----END' lines with proper formatting."
              exit 1
            fi
          fi
          
          echo "✅ SSH key validated successfully"
          
          # Determine connection method
          if [ -n "${{ secrets.TAILSCALE_AUTH_KEY }}" ]; then
            echo "Using Tailscale connection..."
            # Try to get Tailscale IP of the VPS
            VPS_IP=$(tailscale ip -4 ${{ secrets.VPS_TAILSCALE_NAME }} 2>/dev/null || echo "${{ secrets.VPS_HOST }}")
            echo "Connecting to Tailscale IP: $VPS_IP"
          else
            echo "Using direct connection..."
            VPS_IP="${{ secrets.VPS_HOST }}"
          fi
          
          # Try to connect and add to known hosts
          echo "Testing SSH connection to $VPS_IP..."
          ssh-keyscan -H -t rsa,ed25519 $VPS_IP >> ~/.ssh/known_hosts 2>&1 || {
            echo "::warning::Could not scan host keys. Adding StrictHostKeyChecking=no"
            echo "Host $VPS_IP" >> ~/.ssh/config
            echo "  StrictHostKeyChecking no" >> ~/.ssh/config
            echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          }
          
          # Test SSH connection
          echo "Testing SSH connection..."
          ssh -o ConnectTimeout=10 ${{ secrets.VPS_USER }}@$VPS_IP "echo 'SSH connection successful'" || {
            echo "::error::SSH connection failed. Please check:"
            echo "::error::1. If using Tailscale: TAILSCALE_AUTH_KEY and VPS_TAILSCALE_NAME are correct"
            echo "::error::2. If direct: VPS_HOST is accessible from GitHub Actions"
            echo "::error::3. VPS_USER is correct"
            echo "::error::4. SSH key is properly configured on the server"
            echo "::error::5. Firewall allows connection from source IP"
            exit 1
          }
          
          # Export for later use
          echo "VPS_IP=$VPS_IP" >> $GITHUB_ENV
      
      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          # Create deployment script
          cat > deploy_remote.sh << 'EOF'
          #!/bin/bash
          set -e
          
          DEPLOY_PATH="${DEPLOY_PATH:-/home/$USER/familytodo}"
          BACKUP_PATH="${DEPLOY_PATH}/backups"
          
          echo "🚀 Starting deployment..."
          
          # Create directories if they don't exist
          mkdir -p "$DEPLOY_PATH"
          mkdir -p "$BACKUP_PATH"
          
          cd "$DEPLOY_PATH"
          
          # Backup database if it exists
          if [ -f "backend/data/familytodo.db" ]; then
            echo "📦 Backing up database..."
            cp backend/data/familytodo.db "$BACKUP_PATH/familytodo_$(date +%Y%m%d_%H%M%S).db"
            # Keep only last 10 backups
            ls -t "$BACKUP_PATH"/familytodo_*.db | tail -n +11 | xargs -r rm
          fi
          
          # Clone or pull latest code
          if [ ! -d ".git" ]; then
            echo "📥 Cloning repository..."
            git clone https://github.com/vivesm/FamilyToDo.git .
          else
            echo "📥 Pulling latest changes..."
            git fetch origin main
            git reset --hard origin/main
          fi
          
          # Copy production env if doesn't exist
          if [ ! -f "backend/.env" ]; then
            echo "📝 Creating .env from production template..."
            cp backend/.env.production backend/.env
            echo "⚠️  Please update backend/.env with your configuration!"
          fi
          
          # Docker deployment
          if command -v docker-compose &> /dev/null; then
            echo "🐳 Deploying with Docker..."
            docker-compose down || true
            docker-compose build --no-cache
            docker-compose up -d
            
            # Wait for health check
            echo "🏥 Checking health..."
            sleep 10
            if curl -f http://localhost:4000/api/health > /dev/null 2>&1; then
              echo "✅ Deployment successful!"
            else
              echo "❌ Health check failed, rolling back..."
              docker-compose down
              docker-compose up -d
              exit 1
            fi
          else
            # PM2 deployment
            echo "📦 Installing dependencies..."
            cd backend && npm ci --production
            cd ../frontend && npm ci && npm run build
            cd ../backend
            
            # Install PM2 if not present
            if ! command -v pm2 &> /dev/null; then
              echo "📦 Installing PM2..."
              npm install -g pm2
            fi
            
            # Start or restart with PM2
            echo "🔄 Restarting application..."
            pm2 delete familytodo 2>/dev/null || true
            NODE_ENV=production pm2 start npm --name familytodo -- start
            pm2 save
            
            # Wait for health check
            echo "🏥 Checking health..."
            sleep 10
            if curl -f http://localhost:4000/api/health > /dev/null 2>&1; then
              echo "✅ Deployment successful!"
            else
              echo "❌ Health check failed!"
              exit 1
            fi
          fi
          
          echo "🎉 Deployment complete!"
          EOF
          
          # Copy and execute deployment script
          echo "Copying deployment script to VPS..."
          scp -o StrictHostKeyChecking=no deploy_remote.sh ${{ secrets.VPS_USER }}@${VPS_IP}:/tmp/ || {
            echo "::error::Failed to copy deployment script to VPS"
            exit 1
          }
          
          echo "Executing deployment script..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${VPS_IP} "DEPLOY_PATH='${{ secrets.DEPLOY_PATH }}' bash /tmp/deploy_remote.sh" || {
            echo "::error::Deployment script execution failed"
            exit 1
          }
      
      - name: Verify deployment
        run: |
          sleep 5
          curl -f http://${{ secrets.VPS_HOST }}:4000/api/health || exit 1
          echo "✅ Application is running!"
      
      - name: Notify success
        if: success()
        run: echo "🎉 Deployment successful to ${{ secrets.VPS_HOST }}"
      
      - name: Notify failure
        if: failure()
        run: echo "❌ Deployment failed! Check logs for details."